spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todosdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp